name: Deploy DriverDistributor

on:
  push:
    branches:
      - main
      - develop
      - staging

jobs:
  deploy:
    name: Deploy (${{ github.ref_name }})
    runs-on: self-hosted

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set environment variables based on branch
      - name: Set environment variables
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "APP_ENV=develop" >> $GITHUB_ENV
            echo "PORT=5002" >> $GITHUB_ENV
            echo "DB_CONNECTION_STRING=Data Source=.,1433;Initial Catalog=DriverDistributor;User ID=sa;Password=${{secrets.DB_PASSWORD}};Multiple Active Result Sets=True;Trust Server Certificate=True;" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            echo "APP_ENV=staging" >> $GITHUB_ENV
            echo "PORT=5001" >> $GITHUB_ENV
            echo "DB_CONNECTION_STRING=Data Source=.,1433;Initial Catalog=DriverDistributor;User ID=sa;Password=${{secrets.DB_PASSWORD}};Multiple Active Result Sets=True;Trust Server Certificate=True;" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "APP_ENV=production" >> $GITHUB_ENV
            echo "PORT=5000" >> $GITHUB_ENV
            echo "DB_CONNECTION_STRING=Data Source=.,1433;Initial Catalog=DriverDistributor;User ID=sa;Password=${{secrets.DB_PASSWORD}};Multiple Active Result Sets=True;Trust Server Certificate=True;" >> $GITHUB_ENV
          fi

      # 3. Prepare project folder
      - name: Prepare project folder
        run: |
          mkdir -p /home/ubuntu/DriverDistributor/${APP_ENV}
          rsync -av --delete --exclude='.vs' ./ /home/ubuntu/DriverDistributor/${APP_ENV}/

      # 4. Stop old DriverDistributor containers
      - name: Stop old containers
        run: |
          docker stop driverdistributor-${APP_ENV} 2>/dev/null || true
          docker rm driverdistributor-${APP_ENV} 2>/dev/null || true
          docker rmi driverdistributor-${APP_ENV} 2>/dev/null || true

      # 5. Ensure SQL Server container (persistent)
      - name: Ensure SQL Server container
        run: |
          sudo mkdir -p /home/ubuntu/sql_backups 2>/dev/null || true
          sudo chmod -R 777 /home/ubuntu/sql_backups
          docker network create sqlnet 2>/dev/null || true

          if docker ps -a --format '{{.Names}}' | grep -w sqlserver >/dev/null; then
            docker start sqlserver
          else
            docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Arsalan.1461" \
              -p 1433:1433 \
              -v mssql_data:/var/opt/mssql \
              -v /home/ubuntu/sql_backups:/var/opt/mssql/backups \
              --name sqlserver \
              --network sqlnet \
              -d mcr.microsoft.com/mssql/server:2022-latest
          fi

      # 6. Build new DriverDistributor Docker image
      - name: Build Docker image
        run: |
          cd /home/ubuntu/DriverDistributor/${APP_ENV}
          docker build -t driverdistributor-${APP_ENV} .

      # 7. Run DriverDistributor container
      - name: Run DriverDistributor container
        run: |
          docker run -d \
          --name driverdistributor-${APP_ENV} \
          -p ${PORT}:8080 \
          -v driverdata-${APP_ENV}:/app/data \
          -e DOTNET_ENVIRONMENT=${APP_ENV} \
          -e ConnectionStrings__Default="${DB_CONNECTION_STRING}" \
          driverdistributor-${APP_ENV}

      # 8. Deployment complete
      - name: Deployment complete
        run: echo "DriverDistributor ${APP_ENV} container is up and running!"
