name: Deploy DriverDistributor

on:
  push:
    branches:
      - main
      

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Prepare folder
      - name: Prepare project folder
        run: |
          mkdir -p /home/ubuntu/DriverDistributor
          rsync -av --delete --exclude='.vs' ./ /home/ubuntu/DriverDistributor/

      # 3. Stop existing containers
      - name: Stop old containers
        run: |
          docker stop driverdistributor 2>/dev/null || true
          docker rm driverdistributor 2>/dev/null || true
          docker rmi driverdistributor 2>/dev/null || true

      # 4. Ensure SQL Server container is running
      - name: Ensure SQL Server container
        run: |
          if ! docker ps --format '{{.Names}}' | grep -w sqlserver >/dev/null; then
              docker start sqlserver
          fi

      # 5. Build new Docker image
      - name: Build Docker image
        run: |
          cd /home/ubuntu/DriverDistributor
          docker build -t driverdistributor .

      # 6. Run new container
      - name: Run DriverDistributor container
        run: |
          docker run -d --name driverdistributor -p 5000:8080 -v driverdata:/app/data driverdistributor

      - name: Deployment complete
        run: echo "DriverDistributor container is up and running!"
