name: Deploy to MonsterASP via WebDeploy

on:
  push:
    branches:
      - underservice1

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Change if needed

    - name: Publish .NET app
      run: dotnet publish -c Release -o ./publish

    - name: Deploy via WebDeploy
      run: |
       & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
       -verb:sync `
        -source:contentPath="publish" `
        -dest:auto,computerName="https://${{ secrets.WEBDEPLOY_SERVER }}:8172/msdeploy.axd?site=${{ secrets.WEBDEPLOY_SITE }}",userName=${{ secrets.WEBDEPLOY_USERNAME }},password=${{ secrets.WEBDEPLOY_PASSWORD }},authType=Basic `
        -allowUntrusted

